music = {
set: [],
hist: [],
names: {
	BARBER             :"Barber, Samuel                             ",
	BARTOK             :"Bartók, Béla                               ",
	BEETHOVEN          :"Beethoven, Ludwig van                      ",
	BELLINI            :"Bellini, Vincenzo                          ",
	BIZET              :"Bizet, Georges                             ",
	BACHCARLPHILIPPEMAN:"Bach, Carl Philipp Emanuel                 ",
	BACHJOHANNSEBASTIAN:"Bach, Johann Sebastian                     ",
	BERGALBAN          :"Berg, Alban                                ",
	BERLIOZHECTOR      :"Berlioz, Hector                            ",
	BERNSTEINLEONARD   :"Bernstein, Leonard                         ",
	BOCCHERINILUIGI    :"Boccherini, Luigi                          ",
	BORODINALEXANDER   :"Borodin, Alexander                         ",
	BRAHMSJOHANNES     :"Brahms, Johannes                           ",
	BRITTENBENJAMIN    :"Britten, Benjamin                          ",
	BRUCKNERANTON      :"Bruckner, Anton                            ",
	BUSONIFERRUCCIO    :"Busoni, Ferruccio                          ",
	BUXTEHUDEDIETERICH :"Buxtehude, Dieterich                       ",
	BYRDWILLIAM        :"Byrd, William                              ",
	CAGEJOHN           :"Cage, John                                 ",
	CARTERELLIOTT      :"Carter, Elliott                            ",
	CHOPINFRYDERYK     :"Chopin, Fryderyk                           ",
	COPLANDAARON       :"Copland, Aaron                             ",
	CORELLIARCANGELO   :"Corelli, Arcangelo                         ",
	COUPERINFRANÇOIS   :"Couperin, François                         ",
	DEBUSSYCLAUDE      :"Debussy, Claude                            ",
	DELIUSFREDERICK    :"Delius, Frederick                          ",
	DONIZETTIGAETANO   :"Donizetti, Gaetano                         ",
	DOWLANDJOHN        :"Dowland, John                              ",
	DVORÁKANTONIN      :"Dvorák, Antonin                            ",
	ELGAREDWARD        :"Elgar, Edward                              ",
	FALLAMANUELDE      :"Falla, Manuel de                           ",
	FAURÉGABRIEL       :"Fauré, Gabriel                             ",
	FRANCKCESAR        :"Franck, Cesar                              ",
	GERSHWINGEORGE     :"Gershwin, George                           ",
	GLASSPHILIP        :"Glass, Philip                              ",
	GLINKAMIKHAIL      :"Glinka, Mikhail                            ",
	GLUCKCHRISTOPHWRVON:"Gluck, Christoph W.R. von                  ",
	GOUNODCHARLES      :"Gounod, Charles                            ",
	GRAINGERPERCY      :"Grainger, Percy                            ",
	GRANADOSENRIQUE    :"Granados, Enrique                          ",
	GRIEGEDVARD        :"Grieg, Edvard                              ",
	HANDELGEORGEFRIDERI:"Handel, George Frideric                    ",
	HAYDNFRANZJOSEPH   :"Haydn, (Franz) Joseph                      ",
	HINDEMITHPAUL      :"Hindemith, Paul                            ",
	HOLSTGUSTAV        :"Holst, Gustav                              ",
	IVESCHARLES        :"Ives, Charles                              ",
	JANÁCEKLEOS        :"Janácek, Leos                              ",
	JOSQUINDESPREZDESPR:"Josquin Desprez [des Prez, etc.]           ",
	KODÁLYZOLTÁN       :"Kodály, Zoltán                             ",
	LASSOORLANDODIORLAN:"Lasso, Orlando di [Orlandus Lassus, etc.]  ",
	LEHÁRFRANZ         :"Lehár, Franz                               ",
	LIGETIGYÖRGYSÁNDOR :"Ligeti, György Sándor                      ",
	LISZTFRANZ         :"Liszt, Franz                               ",
	MAHLERGUSTAV       :"Mahler, Gustav                             ",
	MARTINUBOHUSLAV    :"Martinu, Bohuslav                          ",
	MASCAGNIPIETRO     :"Mascagni, Pietro                           ",
	MASSENETJULES      :"Massenet, Jules                            ",
	MENDELSSOHNBARTHOLD:"Mendelssohn(-Bartholdy), Felix             ",
	MESSIAENOLIVIER    :"Messiaen, Olivier                          ",
	MEYERBEERGIACOMO   :"Meyerbeer, Giacomo                         ",
	MILHAUDDARIUS      :"Milhaud, Darius                            ",
	MONTEVERDICLAUDIO  :"Monteverdi, Claudio                        ",
	MOZARTWOLFGANGAMADE:"Mozart, Wolfgang Amadeus                   ",
	MUSSORGSKY         :"Mussorgsky, Modest                         ",
	NIELSENCARL        :"Nielsen, Carl                              ",
	OFFENBACHJACQUES   :"Offenbach, Jacques                         ",
	ORFFCARL           :"Orff, Carl                                 ",
	PACHELBELJOHANN    :"Pachelbel, Johann                          ",
	PAGANININICOLÒ     :"Paganini, Nicolò                           ",
	PALESTRINAGIOVANNIP:"Palestrina, Giovanni Pierluigi da          ",
	PIAZZOLLAASTOR     :"Piazzolla, Astor                           ",
	POULENCFRANCIS     :"Poulenc, Francis                           ",
	PROKOFIEVSERGEI    :"Prokofiev, Sergei                          ",
	PUCCINIGIACOMO     :"Puccini, Giacomo                           ",
	PURCELLHENRY       :"Purcell, Henry                             ",
	RACHMANINOVSERGEI  :"Rachmaninov, Sergei                        ",
	RAMEAUJEANPHILIPPE :"Rameau, Jean-Philippe                      ",
	RAVELMAURICE       :"Ravel, Maurice                             ",
	REGERMAX           :"Reger, Max                                 ",
	RIMSKYKORSAKOVNIKOL:"Rimsky-Korsakov, Nikolay                   ",
	RODRIGOJOAQUÍN     :"Rodrigo, Joaquín                           ",
	ROSSINIGIOACHINO   :"Rossini, Gioachino                         ",
	SAINTSAËNSCHARLESCA:"Saint-Saëns, (Charles-)Camille             ",
	SATIEERIK          :"Satie, Erik                                ",
	SCARLATTIALESSANDRO:"Scarlatti, Alessandro                      ",
	SCARLATTIDOMENICO  :"Scarlatti, Domenico                        ",
	SCHOENBERGARNOLD   :"Schoenberg, Arnold                         ",
	SCHUBERTFRANZ      :"Schubert, Franz                            ",
	SCHUMANNROBERT     :"Schumann, Robert                           ",
	SCHÜTZHEINRICH     :"Schütz, Heinrich                           ",
	SCRIABINSKRYABINALE:"Scriabin [Skryabin], Alexander [Aleksandr] ",
	SHOSTAKOVICHDMITRY :"Shostakovich, Dmitry                       ",
	SIBELIUSJEAN       :"Sibelius, Jean                             ",
	SMETANABEDRICH     :"Smetana, Bedrich                           ",
	STOCKHAUSENKARLHEIN:"Stockhausen, Karlheinz                     ",
	STRAUSSJOHANNJR    :"Strauss, Johann Jr.                        ",
	STRAUSSRICHARD     :"Strauss, Richard                           ",
	STRAVINSKYIGOR     :"Stravinsky, Igor                           ",
	SULLIVANARTHUR     :"Sullivan, Arthur                           ",
	TCHAIKOVSKYPYOTRILY:"Tchaikovsky, Pyotr Il'yich                 ",
	TELEMANNGEORGPHILIP:"Telemann, Georg Philipp                    ",
	VAUGHANWILLIAMSRALP:"Vaughan Williams, Ralph                    ",
	VERDIGIUSEPPE      :"Verdi, Giuseppe                            ",
	VILLALOBOSHEITOR   :"Villa-Lobos, Heitor                        ",
	VIVALDIANTONIO     :"Vivaldi, Antonio                           ",
	WAGNERRICHARD      :"Wagner, Richard                            ",
	WALTONWILLIAM      :"Walton, William                            ",
	WEBERCARLMARIAVON  :"Weber, Carl Maria von                      ",
	WEBERNANTONVON     :"Webern, Anton (von)                        ",
	WEILLKURT          :"Weill, Kurt                                ",
	WOLFHUGO           :"Wolf, Hugo                                 ",
},
data: [
    {
        "id": "10152",
        "composer": "BACHJOHANNSEBASTIAN",
        "title": "Partita No. 3 Prelude",
        "year": "",
	"genre": "classical",
        "form": "partita",
        "performer": "",
        "pageurl": "https://archive.org/details/Partita3_prelude",
        "mediaurl": "https://archive.org/download/Partita3_prelude/Partita3_prelude_64kb.mp3"
    },
    {
        "id": "2124",
        "composer": "BACHJOHANNSEBASTIAN",
        "title": "My Heart Ever Faithful",
        "year": "",
	"genre": "classical",
        "form": "hymn",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-88575-LouiseHomer",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88575-LouiseHomer/Homer_88575.mp3"
    },
    {
        "id": "351",
        "composer": "BEETHOVEN",
        "title": "Symphony No. 5",
        "year": "",
	"genre": "classical",
        "form": "symphony",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenSymphonyNo.5",
        "mediaurl": "https://archive.org/download/BeethovenSymphonyNo.5/ToscaniniBeethoven5_64kb.mp3"
    },
    {
        "id": "121",
        "composer": "BEETHOVEN",
        "title": "Symphony No. 8",
        "year": "",
	"genre": "classical",
        "form": "symphony",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenSymphonyNo.8",
        "mediaurl": "https://archive.org/download/BeethovenSymphonyNo.8/01.allegroVivaceEConBrio.mp3"
    },
    {
        "id": "3770",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 6",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.6",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.6/BeethovenSonata6_64kb.mp3"
    },
    {
        "id": "3760",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 26",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.26",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.26/BeethovenPianoSonata26.mp3"
    },
    {
        "id": "3772",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 8",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.8",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.8/BeethovenSonata8_64kb.mp3"
    },
    {
        "id": "2143",
        "composer": "GLINKAMIKHAIL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-88656-FeodorChaliapin",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88656-FeodorChaliapin/Chaliapin_88656_64kb.mp3"
    },
    {
        "id": "2088",
        "composer": "GLUCKCHRISTOPHWRVON",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alma Gluck and Louise Homer",
        "pageurl": "https://archive.org/details/VrsAcoustics-88375-AlmaGluckLouiseHomer",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88375-AlmaGluckLouiseHomer/Gluck_Homer_88375_64kb.mp3"
    },
    {
        "id": "3773",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 9",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.9",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.9/BeethovenPianoSonata9_64kb.mp3"
    },
    {
        "id": "3762",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 28",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.28",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.28/BeethovenPianoSonata28.mp3"
    },
    {
        "id": "56",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 2",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.2",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.2/BeethovenSonata2_64kb.mp3"
    },
    {
        "id": "3769",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 5",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.5",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.5/BeethovenSonata5_64kb.mp3"
    },
    {
        "id": "3747",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 17",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonata17",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonata17/BeethovenPianoSonata17.mp3"
    },
    {
        "id": "109",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 1",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.1",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.1/BeethovenSonata1_64kb.mp3"
    },
    {
        "id": "111",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 15",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonata15",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonata15/BeethovenPianoSonata15_64kb.mp3"
    },
    {
        "id": "120",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 13",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonata13",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonata13/BeethovenPianoSonata13_64kb.mp3"
    },
    {
        "id": "350",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 16",
        "year": "",
	"genre": "classical",
        "form": "solo instrument",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonata16",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonata16/BeethovenPianoSonata16_64kb.mp3"
    },
    {
        "id": "3757",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 23",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.23",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.23/BeethovenPianoSonata23.mp3"
    },
    {
        "id": "3759",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 25",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.25",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.25/BeethovenPianoSonata25.mp3"
    },
    {
        "id": "3758",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 24",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.24",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.24/BeethovenPianoSonata24.mp3"
    },
    {
        "id": "3753",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 18",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.18",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.18/BeethovenPianoSonata18_64kb.mp3"
    },
    {
        "id": "3755",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 20",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.20",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.20/BeethovenPianoSonata20_64kb.mp3"
    },
    {
        "id": "3756",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 21 Waldstein",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.21Waldstein",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.21Waldstein/BeethovenPianoSonata21_64kb.mp3"
    },
    {
        "id": "3771",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 7",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.7",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.7/BeethovenSonata7_64kb.mp3"
    },
    {
        "id": "5999",
        "composer": "BEETHOVEN",
        "title": "Menuett G flat major & Valse bluette",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0192-03",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0192-03/EDIS-SRP-0192-03.mp3"
    },
    {
        "id": "3763",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 29",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.29",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.29/BeethovenPianoSonata29.mp3"
    },
    {
        "id": "3764",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 3",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.3",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.3/BeethovenSonata3_64kb.mp3"
    },
    {
        "id": "3765",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 30",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.30",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.30/BeethovenSonata30.mp3"
    },
    {
        "id": "3766",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 31",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.31",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.31/BeethovenSonata31.mp3"
    },
    {
        "id": "3767",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 32",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.32",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.32/BeethovenPianoSonata32.mp3"
    },
    {
        "id": "3768",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 4",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.4",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.4/BeethovenSonata4_64kb.mp3"
    },
    {
        "id": "3754",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 19",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.19",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.19/BeethovenPianoSonata19_64kb.mp3"
    },
    {
        "id": "3746",
        "composer": "BEETHOVEN",
        "title": "Piano Concerto No. 5 Emperor",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoConcerto5Emperor",
        "mediaurl": "https://archive.org/download/BeethovenPianoConcerto5Emperor/BeethovenEmperor.mp3"
    },
    {
        "id": "3761",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 27",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.27",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.27/BeethovenPianoSonata27.mp3"
    },
    {
        "id": "3748",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 22",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonata22",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonata22/BeethovenPianoSonata22.mp3"
    },
    {
        "id": "3749",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 10",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.10",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.10/BeethovenSonata10_64kb.mp3"
    },
    {
        "id": "3750",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 11",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.11",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.11/BeethovenSonata11.mp3"
    },
    {
        "id": "3751",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 12",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.12",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.12/BeethovenPianoSonata12_64kb.mp3"
    },
    {
        "id": "3752",
        "composer": "BEETHOVEN",
        "title": "Piano Sonata No. 14,",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BeethovenPianoSonataNo.14moonlight",
        "mediaurl": "https://archive.org/download/BeethovenPianoSonataNo.14moonlight/BeethovenPianoSonata14.mp3"
    },
    {
        "id": "9581",
        "composer": "BIZET",
        "title": "Mi Par D'udir Ancora",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/MiParDudirAncora",
        "mediaurl": "https://archive.org/download/MiParDudirAncora/Caruso_Mi_Par_Dudir_Ancora_64kb.mp3"
    },
    {
        "id": "7847",
        "composer": "BIZET",
        "title": "Il fior che avevi a me dato",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Il_fior_che_avevi_a_me_dato",
        "mediaurl": "https://archive.org/download/Il_fior_che_avevi_a_me_dato/Caruso_Il_Fior_Che_Avevi_A_Me_Dato_64kb.mp3"
    },
    {
        "id": "8278",
        "composer": "BIZET",
        "title": "Je Crois Entendre Encore",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Je_Crois_Entendre_Encore",
        "mediaurl": "https://archive.org/download/Je_Crois_Entendre_Encore/Caruso_Je_Crois_Entendre_Encore_64kb.mp3"
    },
    {
        "id": "8796",
        "composer": "BIZET",
        "title": "La Fleur Que Tu M'Avais Jetee",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/La_Fleur_Que_Tu_MAvais_Jetee",
        "mediaurl": "https://archive.org/download/La_Fleur_Que_Tu_MAvais_Jetee/Caruso_La_fleur_que_tu_m_avais_jetee_64kb.mp3"
    },
    {
        "id": "1996",
        "composer": "BEETHOVEN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74792-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74792-FlonzaleyQuartet/FlonzaleyQuartet_74792_64kb.mp3"
    },
    {
        "id": "2144",
        "composer": "BEETHOVEN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-88657-FeodorChaliapin",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88657-FeodorChaliapin/Chaliapin_88657_64kb.mp3"
    },
    {
        "id": "1969",
        "composer": "BEETHOVEN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74661-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74661-PhiladelphiaSymphonyOrchestra/PhilSymph_74661_64kb.mp3"
    },
    {
        "id": "1979",
        "composer": "BEETHOVEN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74710-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74710-FlonzaleyQuartet/FlonzaleyQuartet_74710_64kb.mp3"
    },
    {
        "id": "1990",
        "composer": "BEETHOVEN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74754-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74754-FlonzaleyQuartet/FlonzaleyQuartet_74754_64kb.mp3"
    },
    {
        "id": "1984",
        "composer": "BRAHMSJOHANNES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74722-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74722-PhiladelphiaSymphonyOrchestra/PhilSymph_74722_64kb.mp3"
    },
    {
        "id": "1973",
        "composer": "BRAHMSJOHANNES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74685-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74685-FlonzaleyQuartet/FlonzaleyQuartet_74685_64kb.mp3"
    },
    {
        "id": "4593",
        "composer": "BRITTENBENJAMIN",
        "title": "The Turn of the Screw",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/BrittenTheTurnOfTheScrew",
        "mediaurl": "https://archive.org/download/BrittenTheTurnOfTheScrew/TurnOfTheScrewActOne.mp3"
    },
    {
        "id": "2864",
        "composer": "CAGEJOHN",
        "title": "A Bird in a Gilded Cage",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ABirdInAGildedCage1900",
        "mediaurl": "https://archive.org/download/ABirdInAGildedCage1900/06-ABirdInAGildedCage1900_64kb.mp3"
    },
    {
        "id": "1798",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-6448b-IgnaceJanPaderewski",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6448b-IgnaceJanPaderewski/Paderewski_6448B_64kb.mp3"
    },
    {
        "id": "1957",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74623-AlfredCortot",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74623-AlfredCortot/Cortot_74623_64kb.mp3"
    },
    {
        "id": "1797",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-6448a-IgnaceJanPaderewski",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6448a-IgnaceJanPaderewski/Paderewski_6448A.mp3"
    },
    {
        "id": "5102",
        "composer": "CHOPINFRYDERYK",
        "title": "Works for Piano",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ChopinWorksForPiano",
        "mediaurl": "https://archive.org/download/ChopinWorksForPiano/ImpromptuInAFlatOp.29No.1.mp3"
    },
    {
        "id": "2236",
        "composer": "CHOPINFRYDERYK",
        "title": "Waltz in E Minor",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/WaltzInEMinor",
        "mediaurl": "https://archive.org/download/WaltzInEMinor/Waltz_in_E_64kb.mp3"
    },
    {
        "id": "1933",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74530-IgnaceJanPaderewski",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74530-IgnaceJanPaderewski/Paderewski_74530_64kb.mp3"
    },
    {
        "id": "1971",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74679-SergeiRachmaninoff",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74679-SergeiRachmaninoff/Rachmaninoff_74679_64kb.mp3"
    },
    {
        "id": "1907",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74313-VladimirDePachmann",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74313-VladimirDePachmann/DePachmann_74313_64kb.mp3"
    },
    {
        "id": "2083",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-88322-IgnaceJanPaderewski",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88322-IgnaceJanPaderewski/Paderewski_88322_64kb.mp3"
    },
    {
        "id": "1905",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74304-VladimirDePachmann",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74304-VladimirDePachmann/DePachmann_74304_64kb.mp3"
    },
    {
        "id": "1846",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74159-WilhelmBackhaus",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74159-WilhelmBackhaus/Backhaus_74159_64kb.mp3"
    },
    {
        "id": "1828",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74052-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74052-MischaElman/Elman_74052_64kb.mp3"
    },
    {
        "id": "1805",
        "composer": "CHOPINFRYDERYK",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-6480b-VladimirDePachmann",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6480b-VladimirDePachmann/DePachmann_6480b_64kb.mp3"
    },
    {
        "id": "5101",
        "composer": "CHOPINFRYDERYK",
        "title": "Sonata No. 2",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Chopin_Sonata_2",
        "mediaurl": "https://archive.org/download/Chopin_Sonata_2/ChopinSonata2_64kb.mp3"
    },
    {
        "id": "5098",
        "composer": "CHOPINFRYDERYK",
        "title": "Fourteen Waltzes",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ChopinFourteenWaltzes",
        "mediaurl": "https://archive.org/download/ChopinFourteenWaltzes/01%20No.%201%20in%20E%20flat%2C%20Op.%2018%20Grande%20valse%20brilliante.mp3"
    },
    {
        "id": "6038",
        "composer": "CHOPINFRYDERYK",
        "title": "Two etudes: Etude nouvelle in A flat & Etude in C major, Op. 10, no. 1",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0197-13",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0197-13/EDIS-SRP-0197-13.mp3"
    },
    {
        "id": "3410",
        "composer": "DEBUSSYCLAUDE",
        "title": "Arabesques Nos. 1 & 2",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ArabesquesNos.12",
        "mediaurl": "https://archive.org/download/ArabesquesNos.12/DebussyArabesque12_64kb.mp3"
    },
    {
        "id": "4867",
        "composer": "DONIZETTIGAETANO",
        "title": "Angelo Casto e bel",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoAngeloCastoEBel",
        "mediaurl": "https://archive.org/download/CarusoAngeloCastoEBel/Caruso_Angelo_Casto_E_Bel.mp3"
    },
    {
        "id": "4868",
        "composer": "DONIZETTIGAETANO",
        "title": "Com'e Gentil",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoComeGentil",
        "mediaurl": "https://archive.org/download/CarusoComeGentil/Caruso_Come_Gentil.mp3"
    },
    {
        "id": "1961",
        "composer": "DVOR\u00c1KANTONIN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74631-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74631-PhiladelphiaSymphonyOrchestra/PhilSymph_74631_64kb.mp3"
    },
    {
        "id": "6036",
        "composer": "DVOR\u00c1KANTONIN",
        "title": "Slavonic dance No. 1",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0197-11",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0197-11/EDIS-SRP-0197-11.mp3"
    },
    {
        "id": "1847",
        "composer": "DVOR\u00c1KANTONIN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74163-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74163-MischaElman/Elman_74163_64kb.mp3"
    },
    {
        "id": "3314",
        "composer": "GERSHWINGEORGE",
        "title": "An American In Paris",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/AnAmericanInParis",
        "mediaurl": "https://archive.org/download/AnAmericanInParis/AnAmericanInParis_64kb.mp3"
    },
    {
        "id": "10610",
        "composer": "GERSHWINGEORGE",
        "title": "Rhapsody In Blue Part 1",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/rhapblue11924",
        "mediaurl": "https://archive.org/download/rhapblue11924/rhapblue11924.mp3"
    },
    {
        "id": "1918",
        "composer": "GLUCKCHRISTOPHWRVON",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/VrsAcoustics-74459-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74459-MischaElman/Elman_74459_64kb.mp3"
    },
    {
        "id": "3221",
        "composer": "GLUCKCHRISTOPHWRVON",
        "title": "Alma Gluck - Musetta",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/AlmaGluck-Musetta",
        "mediaurl": "https://archive.org/download/AlmaGluck-Musetta/AlmaGluck-MusettaWaltz_64kb.mp3"
    },
    {
        "id": "1255",
        "composer": "GLUCKCHRISTOPHWRVON",
        "title": "The little old log cabin in the lane",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/TheLittleOldLogCabinInTheLane",
        "mediaurl": "https://archive.org/download/TheLittleOldLogCabinInTheLane/TheLittleOldLogCabinInTheLane.mp3"
    },
    {
        "id": "2125",
        "composer": "GLUCKCHRISTOPHWRVON",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alma Gluck and Louise Homer",
        "pageurl": "https://archive.org/details/VrsAcoustics-88577-AlmaGluckLouiseHomer",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88577-AlmaGluckLouiseHomer/Gluck-Homer_88577_64kb.mp3"
    },
    {
        "id": "7866",
        "composer": "GOUNODCHARLES",
        "title": "Il se fait tard",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/IlSeFaitTard",
        "mediaurl": "https://archive.org/download/IlSeFaitTard/Il_se_fait_tard_64kb.mp3"
    },
    {
        "id": "2009",
        "composer": "GOUNODCHARLES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Pol Plancon",
        "pageurl": "https://archive.org/details/VrsAcoustics-85065-PolPlancon",
        "mediaurl": "https://archive.org/download/VrsAcoustics-85065-PolPlancon/85065_Plancon.mp3"
    },
    {
        "id": "4871",
        "composer": "GOUNODCHARLES",
        "title": "Inspirez-moi, race divine",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoInspirez-moiRaceDivine",
        "mediaurl": "https://archive.org/download/CarusoInspirez-moiRaceDivine/Caruso_Inspirez-Moi_Race_Divine.mp3"
    },
    {
        "id": "2026",
        "composer": "GOUNODCHARLES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Emma Eames & Josef Hollman",
        "pageurl": "https://archive.org/details/VrsAcoustics-88016-EmmaEamesJosefHollman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88016-EmmaEamesJosefHollman/Eames_88016_64kb.mp3"
    },
    {
        "id": "2159",
        "composer": "GOUNODCHARLES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "John McCormack & Fritz Kreisler",
        "pageurl": "https://archive.org/details/VrsAcoustics-89104-JohnMccormackFritzKreisler",
        "mediaurl": "https://archive.org/download/VrsAcoustics-89104-JohnMccormackFritzKreisler/McCormack-Kreisler_89104_64kb.mp3"
    },
    {
        "id": "2054",
        "composer": "GOUNODCHARLES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Emma Calve",
        "pageurl": "https://archive.org/details/VrsAcoustics-88119-EmmaCalve",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88119-EmmaCalve/Calve_88119-1_64kb.mp3"
    },
    {
        "id": "4877",
        "composer": "GOUNODCHARLES",
        "title": "Mon coeur est penetre d'epouvante",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoMonCoeurEstPenetreDepouvante",
        "mediaurl": "https://archive.org/download/CarusoMonCoeurEstPenetreDepouvante/Caruso_Mon_coeur_est_penetre_depouva_64kb.mp3"
    },
    {
        "id": "2156",
        "composer": "GOUNODCHARLES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Nellie Melba & Jan Kubelik",
        "pageurl": "https://archive.org/details/VrsAcoustics-89073-NellieMelbaJanKubelik",
        "mediaurl": "https://archive.org/download/VrsAcoustics-89073-NellieMelbaJanKubelik/Melba-Kubelik_89073_64kb.mp3"
    },
    {
        "id": "2119",
        "composer": "GOUNODCHARLES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Emmy Destinn",
        "pageurl": "https://archive.org/details/VrsAcoustics-88562-EmmyDestinn",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88562-EmmyDestinn/Destinn_88562_64kb.mp3"
    },
    {
        "id": "1944",
        "composer": "GRAINGERPERCY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Flonzaley Quartet",
        "pageurl": "https://archive.org/details/VrsAcoustics-74580-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74580-FlonzaleyQuartet/FlonzaleyQuartet_74580_64kb.mp3"
    },
    {
        "id": "1868",
        "composer": "GRIEGEDVARD",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Luisa Tetrazzini",
        "pageurl": "https://archive.org/details/VrsAcoustics-88508-LuisaTetrazzini",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88508-LuisaTetrazzini/Tetrazzini_88508_64kb.mp3"
    },
    {
        "id": "1964",
        "composer": "GRIEGEDVARD",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Mischa Elman",
        "pageurl": "https://archive.org/details/VrsAcoustics-74643-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74643-MischaElman/Elman_74643_64kb.mp3"
    },
    {
        "id": "7102",
        "composer": "GRIEGEDVARD",
        "title": "Piano Concerto",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/GriegPianoConcerto",
        "mediaurl": "https://archive.org/download/GriegPianoConcerto/Grieg-PianoConcerto_64kb.mp3"
    },
    {
        "id": "1995",
        "composer": "GRIEGEDVARD",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Olga Samaroff",
        "pageurl": "https://archive.org/details/VrsAcoustics-74785-OlgaSamaroff",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74785-OlgaSamaroff/Samaroff_74785_64kb.mp3"
    },
    {
        "id": "4878",
        "composer": "HANDELGEORGEFRIDERIC",
        "title": "Ombra mai fu",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoOmbraMaiFu",
        "mediaurl": "https://archive.org/download/CarusoOmbraMaiFu/Caruso_Ombra_Mai_Fu.mp3"
    },
    {
        "id": "7195",
        "composer": "HANDELGEORGEFRIDERIC",
        "title": "The Harmonious Blacksmith",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/HandelTheHarmoniousBlacksmithlandowska",
        "mediaurl": "https://archive.org/download/HandelTheHarmoniousBlacksmithlandowska/Handel-TheHarmoniousBlacksmithlandowska.mp3"
    },
    {
        "id": "5908",
        "composer": "HANDELGEORGEFRIDERIC",
        "title": "Hallelujah chorus - Messiah",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0195-06",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0195-06/EDIS-SRP-0195-06.mp3"
    },
    {
        "id": "7194",
        "composer": "HANDELGEORGEFRIDERIC",
        "title": "The Harmonious Blacksmith",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/HandelTheHarmoniousBlacksmithcortot",
        "mediaurl": "https://archive.org/download/HandelTheHarmoniousBlacksmithcortot/Handel-TheHarmoniousBlacksmithcortot.mp3"
    },
    {
        "id": "6034",
        "composer": "BEETHOVEN",
        "title": "Moonlight sonata",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0197-09",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0197-09/EDIS-SRP-0197-09.mp3"
    },
    {
        "id": "1937",
        "composer": "MENDELSSOHNBARTHOLDY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-74560-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74560-PhiladelphiaSymphonyOrchestra/PhilSymph_74560_64kb.mp3"
    },
    {
        "id": "5976",
        "composer": "HANDELGEORGEFRIDERIC",
        "title": "Handel festival: 'Israel In Egypt' - excerpt",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0154-17",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0154-17/EDIS-SRP-0154-17.mp3"
    },
    {
        "id": "1820",
        "composer": "HANDELGEORGEFRIDERIC",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Wilhelm Backhaus",
        "pageurl": "https://archive.org/details/VrsAcoustics-71041-WilhelmBackhaus",
        "mediaurl": "https://archive.org/download/VrsAcoustics-71041-WilhelmBackhaus/Backhaus_71041_64kb.mp3"
    },
    {
        "id": "7207",
        "composer": "HANDELGEORGEFRIDERIC",
        "title": "Harmonious Blacksmith",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Harmonious_Blacksmith",
        "mediaurl": "https://archive.org/download/Harmonious_Blacksmith/HarmoniousBlacksmith_64kb.mp3"
    },
    {
        "id": "1986",
        "composer": "HAYDNFRANZJOSEPH",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Flonzaley Quartet",
        "pageurl": "https://archive.org/details/VrsAcoustics-74726-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74726-FlonzaleyQuartet/FlonzaleyQuartet_74726_64kb.mp3"
    },
    {
        "id": "7451",
        "composer": "HAYDNFRANZJOSEPH",
        "title": "Symphony No 94 Surprise",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Haydn_Symphony_No_94_Surprise",
        "mediaurl": "https://archive.org/download/Haydn_Symphony_No_94_Surprise/HaydnSurprise_64kb.mp3"
    },
    {
        "id": "1976",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Olga Samaroff",
        "pageurl": "https://archive.org/details/VrsAcoustics-74696-OlgaSamaroff",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74696-OlgaSamaroff/Samaroff_74696_64kb.mp3"
    },
    {
        "id": "2068",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Louise Homer",
        "pageurl": "https://archive.org/details/VrsAcoustics-88204-LouiseHomer",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88204-LouiseHomer/Homer_88204_64kb.mp3"
    },
    {
        "id": "1947",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alfred Cortot",
        "pageurl": "https://archive.org/details/VrsAcoustics-74589-AlfredCortot",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74589-AlfredCortot/Cortot_74589_64kb.mp3"
    },
    {
        "id": "1966",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-74647-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74647-PhiladelphiaSymphonyOrchestra/PhilSymph_74647_64kb.mp3"
    },
    {
        "id": "306",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Emmy Destinn",
        "pageurl": "https://archive.org/details/VrsAcoustics-88568-EmmyDestinn",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88568-EmmyDestinn/Destinn_88568_64kb.mp3"
    },
    {
        "id": "1997",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Olga Samaroff",
        "pageurl": "https://archive.org/details/VrsAcoustics-74794-OlgaSamaroff",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74794-OlgaSamaroff/Samaroff_74794_64kb.mp3"
    },
    {
        "id": "1999",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Ignace Jan Paderewski",
        "pageurl": "https://archive.org/details/VrsAcoustics-7480574806-IgnaceJanPaderewski",
        "mediaurl": "https://archive.org/download/VrsAcoustics-7480574806-IgnaceJanPaderewski/Paderewski_74805-06_64kb.mp3"
    },
    {
        "id": "1799",
        "composer": "LISZTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Olga Samaroff",
        "pageurl": "https://archive.org/details/VrsAcoustics-6450-OlgaSamaroff",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6450-OlgaSamaroff/Samaroff_6450_64kb.mp3"
    },
    {
        "id": "2954",
        "composer": "MASCAGNIPIETRO",
        "title": "Addio Alla Madre",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Addio_Alla_Madre",
        "mediaurl": "https://archive.org/download/Addio_Alla_Madre/Addio_Alla_Madre_64kb.mp3"
    },
    {
        "id": "1916",
        "composer": "MASCAGNIPIETRO",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Giovanni Martinelli",
        "pageurl": "https://archive.org/details/VrsAcoustics-74426-GiovanniMartinelli",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74426-GiovanniMartinelli/Martinelli_74426_64kb.mp3"
    },
    {
        "id": "9683",
        "composer": "MASCAGNIPIETRO",
        "title": "Musica Proibita",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Musica_Proibita",
        "mediaurl": "https://archive.org/download/Musica_Proibita/Caruso_Musica_Probita_64kb.mp3"
    },
    {
        "id": "1911",
        "composer": "MASSENETJULES",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Mischa Elman",
        "pageurl": "https://archive.org/details/VrsAcoustics-74341-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74341-MischaElman/Elman_74341_64kb.mp3"
    },
    {
        "id": "5094",
        "composer": "MASSENETJULES",
        "title": "Chiudi gli Occhi",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Chiudi_gli_Occhi",
        "mediaurl": "https://archive.org/download/Chiudi_gli_Occhi/Chiudi_Gli_Occhi_64kb.mp3"
    },
    {
        "id": "2007",
        "composer": "MENDELSSOHNBARTHOLDY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Maud Powell",
        "pageurl": "https://archive.org/details/VrsAcoustics-85040-MaudPowell",
        "mediaurl": "https://archive.org/download/VrsAcoustics-85040-MaudPowell/Powell_85040_64kb.mp3"
    },
    {
        "id": "882",
        "composer": "MENDELSSOHNBARTHOLDY",
        "title": "Spinning Song",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/SpinningSong",
        "mediaurl": "https://archive.org/download/SpinningSong/Spinning_Song_64kb.mp3"
    },
    {
        "id": "1983",
        "composer": "MENDELSSOHNBARTHOLDY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Jascha Heifetz",
        "pageurl": "https://archive.org/details/VrsAcoustics-74721-JaschaHeifetz",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74721-JaschaHeifetz/Heifetz_74721_64kb.mp3"
    },
    {
        "id": "1952",
        "composer": "MENDELSSOHNBARTHOLDY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Mischa Elman",
        "pageurl": "https://archive.org/details/VrsAcoustics-74607-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74607-MischaElman/Elman_74607_64kb.mp3"
    },
    {
        "id": "591",
        "composer": "MENDELSSOHNBARTHOLDY",
        "title": "Scherzo by Mendelssohn",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ScherzoByMendelssohn",
        "mediaurl": "https://archive.org/download/ScherzoByMendelssohn/Rachmaninoff_Scherzo_64kb.mp3"
    },
    {
        "id": "2002",
        "composer": "MENDELSSOHNBARTHOLDY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alfred Cortot",
        "pageurl": "https://archive.org/details/VrsAcoustics-74810-AlfredCortot",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74810-AlfredCortot/Cortot_74810_64kb.mp3"
    },
    {
        "id": "2744",
        "composer": "MEYERBEERGIACOMO",
        "title": "Ah, qual soave vision",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Ah_qual_soave_vision",
        "mediaurl": "https://archive.org/download/Ah_qual_soave_vision/Ah_qual_soave_vision_64kb.mp3"
    },
    {
        "id": "4883",
        "composer": "MEYERBEERGIACOMO",
        "title": "Qui sotto il ciel",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoQuiSottoIlCiel",
        "mediaurl": "https://archive.org/download/CarusoQuiSottoIlCiel/Caruso_quiSottoIlCiel_64kb.mp3"
    },
    {
        "id": "1943",
        "composer": "MOZARTWOLFGANGAMADEU",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Flonzaley Quartet",
        "pageurl": "https://archive.org/details/VrsAcoustics-74579-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74579-FlonzaleyQuartet/FlonzaleyQuartet_74579_64kb.mp3"
    },
    {
        "id": "279",
        "composer": "MOZARTWOLFGANGAMADEU",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Flonzaley Quartet",
        "pageurl": "https://archive.org/details/VrsAcoustics-74596-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74596-FlonzaleyQuartet/FlonzaleyQuartet_74596_64kb.mp3"
    },
    {
        "id": "6017",
        "composer": "MOZARTWOLFGANGAMADEU",
        "title": "Gloria - The twelfth mass",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0195-05",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0195-05/EDIS-SRP-0195-05.mp3"
    },
    {
        "id": "1953",
        "composer": "MOZARTWOLFGANGAMADEU",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-74609-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74609-PhiladelphiaSymphonyOrchestra/PhilSymph_74609_64kb.mp3"
    },
    {
        "id": "1968",
        "composer": "MOZARTWOLFGANGAMADEU",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Flonzaley Quartet",
        "pageurl": "https://archive.org/details/VrsAcoustics-74652-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74652-FlonzaleyQuartet/FlonzaleyQuartet_74652_64kb.mp3"
    },
    {
        "id": "6051",
        "composer": "MOZARTWOLFGANGAMADEU",
        "title": "Quartet in G, 1st movement- part 1",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0199-04",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0199-04/EDIS-SRP-0199-04.mp3"
    },
    {
        "id": "2146",
        "composer": "MUSSORGSKY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Feodor Chaliapin",
        "pageurl": "https://archive.org/details/VrsAcoustics-88659-FeodorChaliapin",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88659-FeodorChaliapin/Chaliapin_88659_64kb.mp3"
    },
    {
        "id": "2136",
        "composer": "MUSSORGSKY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Feodor Chaliapin",
        "pageurl": "https://archive.org/details/VrsAcoustics-88644-FeodorChaliapin",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88644-FeodorChaliapin/Chaliapin_88644_64kb.mp3"
    },
    {
        "id": "161",
        "composer": "NIELSENCARL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alice Nielsen & Florencio Constantino",
        "pageurl": "https://archive.org/details/VrsAcoustics-74064-AliceNielsenFlorencioConstantino",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74064-AliceNielsenFlorencioConstantino/Nielsen-Constantino_74064_64kb.mp3"
    },
    {
        "id": "1836",
        "composer": "NIELSENCARL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alice Nielsen",
        "pageurl": "https://archive.org/details/VrsAcoustics-74107-AliceNielsen",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74107-AliceNielsen/Nielsen_74107_64kb.mp3"
    },
    {
        "id": "265",
        "composer": "NIELSENCARL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alice Nielsen",
        "pageurl": "https://archive.org/details/VrsAcoustics-74107-AliceNielsen_435",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74107-AliceNielsen_435/Nielsen_74107_64kb.mp3"
    },
    {
        "id": "263",
        "composer": "NIELSENCARL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alice Nielsen & Florencio Constantino",
        "pageurl": "https://archive.org/details/VrsAcoustics-74076-AliceNielsenFlorencioConstantino",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74076-AliceNielsenFlorencioConstantino/Nielsen-Constantino_74076_64kb.mp3"
    },
    {
        "id": "266",
        "composer": "NIELSENCARL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alice Nielsen",
        "pageurl": "https://archive.org/details/VrsAcoustics-74121-AliceNielsen",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74121-AliceNielsen/Nielsen_74121_64kb.mp3"
    },
    {
        "id": "1838",
        "composer": "NIELSENCARL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alice Nielsen",
        "pageurl": "https://archive.org/details/VrsAcoustics-74121-AliceNielsen_22",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74121-AliceNielsen_22/Nielsen_74121_64kb.mp3"
    },
    {
        "id": "160",
        "composer": "NIELSENCARL",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alice Nielsen & Florencio Constantino",
        "pageurl": "https://archive.org/details/VrsAcoustics-74063-AliceNielsenFlorencioConstantino",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74063-AliceNielsenFlorencioConstantino/Nielsen-Constantino_74063_64kb.mp3"
    },
    {
        "id": "2189",
        "composer": "PALESTRINAGIOVANNIPI",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Sistine Chapel Choir - 6442A",
        "pageurl": "https://archive.org/details/VrsAcoustics-SistineChapelChoir-6442a",
        "mediaurl": "https://archive.org/download/VrsAcoustics-SistineChapelChoir-6442a/SistineChoir_6442A_64kb.mp3"
    },
    {
        "id": "1795",
        "composer": "PALESTRINAGIOVANNIPI",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Sistine Chapel Choir",
        "pageurl": "https://archive.org/details/VrsAcoustics-6442b-SistineChapelChoir",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6442b-SistineChapelChoir/SistineChoir_6442B_64kb.mp3"
    },
    {
        "id": "3307",
        "composer": "PUCCINIGIACOMO",
        "title": "Amore O Grillo",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Amore_O_Grillo",
        "mediaurl": "https://archive.org/download/Amore_O_Grillo/Amore_o_grillo_64kb.mp3"
    },
    {
        "id": "9855",
        "composer": "PUCCINIGIACOMO",
        "title": "Non ve l'avevo detto",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Non_ve_lavevo_detto",
        "mediaurl": "https://archive.org/download/Non_ve_lavevo_detto/Caruso_Non_ve_lavevo_64kb.mp3"
    },
    {
        "id": "6003",
        "composer": "PUCCINIGIACOMO",
        "title": "Sono un poeta - La Boheme",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0194-04",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0194-04/EDIS-SRP-0194-04.mp3"
    },
    {
        "id": "2955",
        "composer": "PUCCINIGIACOMO",
        "title": "Addio Dolce Svegliare Alla Mattina",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/AddioDolceSvegliareAllaMattina",
        "mediaurl": ""
    },
    {
        "id": "4869",
        "composer": "PUCCINIGIACOMO",
        "title": "E lucevan le stelle",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoELucevanLeStelle",
        "mediaurl": "https://archive.org/download/CarusoELucevanLeStelle/Caruso_E_lucevan_le_stelle01.mp3"
    },
    {
        "id": "1115",
        "composer": "RACHMANINOVSERGEI",
        "title": "The Art of Rachmaninov Vol. 2, Side 2",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/TheArtOfRachmaninovVol.2Side2",
        "mediaurl": "https://archive.org/download/TheArtOfRachmaninovVol.2Side2/Borodin-Scherzo.mp3"
    },
    {
        "id": "1114",
        "composer": "RACHMANINOVSERGEI",
        "title": "The Art of Rachmaninov Vol. 2, Side 1",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/TheArtOfRachmaninovVol.2",
        "mediaurl": "https://archive.org/download/TheArtOfRachmaninovVol.2/Bach-PreludeFromPartita3ForViolin.mp3"
    },
    {
        "id": "10491",
        "composer": "RAVELMAURICE",
        "title": "Concerto for the Left Hand Alone",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/RavelConcertoForTheLeftHandAlone",
        "mediaurl": "https://archive.org/download/RavelConcertoForTheLeftHandAlone/RavelLeftHandConcerto.mp3"
    },
    {
        "id": "6031",
        "composer": "ROSSINIGIOACHINO",
        "title": "William Tell overture - part 2",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0197-05",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0197-05/EDIS-SRP-0197-05.mp3"
    },
    {
        "id": "1786",
        "composer": "ROSSINIGIOACHINO",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Jose Mardones",
        "pageurl": "https://archive.org/details/VrsAcoustics-6420b-JoseMardones",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6420b-JoseMardones/Mardones_6420B_64kb.mp3"
    },
    {
        "id": "2016",
        "composer": "ROSSINIGIOACHINO",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Lucrezia Bori",
        "pageurl": "https://archive.org/details/VrsAcoustics-87181-LucreziaBori",
        "mediaurl": "https://archive.org/download/VrsAcoustics-87181-LucreziaBori/87181_Bori_64kb.mp3"
    },
    {
        "id": "686",
        "composer": "SCHUBERTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Fritz Kreisler",
        "pageurl": "https://archive.org/details/VrsAcoustics-74202-FritzKreisler",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74202-FritzKreisler/Kreisler_74202_64kb.mp3"
    },
    {
        "id": "599",
        "composer": "SCHUBERTFRANZ",
        "title": "Serenade",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/SchubertSerenade_441",
        "mediaurl": "https://archive.org/download/SchubertSerenade_441/SchubertSerenade_64kb.mp3"
    },
    {
        "id": "1806",
        "composer": "SCHUBERTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Ignace Jan Paderewski",
        "pageurl": "https://archive.org/details/VrsAcoustics-6482-IgnaceJanPaderewski",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6482-IgnaceJanPaderewski/Paderewski_6482_64kb.mp3"
    },
    {
        "id": "6042",
        "composer": "SCHUBERTFRANZ",
        "title": "Trio no. 1 in B flat, part 1-1st movement- allegro moderato, Op. 99",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0198-07",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0198-07/EDIS-SRP-0198-07.mp3"
    },
    {
        "id": "1910",
        "composer": "SCHUBERTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Mischa Elman",
        "pageurl": "https://archive.org/details/VrsAcoustics-74339-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74339-MischaElman/Elman_74339.mp3"
    },
    {
        "id": "2163",
        "composer": "SCHUBERTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Louise Homer & Louise Homer Stires",
        "pageurl": "https://archive.org/details/VrsAcoustics-89159-LouiseHomerLouiseHomerStires",
        "mediaurl": "https://archive.org/download/VrsAcoustics-89159-LouiseHomerLouiseHomerStires/Homer-Homer_89159_64kb.mp3"
    },
    {
        "id": "600",
        "composer": "SCHUBERTFRANZ",
        "title": "Sonata in B flat Major, Op. Posthumous",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/SchubertSonataInBFlatMajorOp.Posthumous",
        "mediaurl": "https://archive.org/download/SchubertSonataInBFlatMajorOp.Posthumous/SchubertSonata.mp3"
    },
    {
        "id": "1850",
        "composer": "SCHUBERTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Mischa Elman",
        "pageurl": "https://archive.org/details/VrsAcoustics-74167-MischaElman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74167-MischaElman/Elman_74167_64kb.mp3"
    },
    {
        "id": "5118",
        "composer": "SCHUBERTFRANZ",
        "title": "Christmas chimes",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ChristmasChimes",
        "mediaurl": "https://archive.org/download/ChristmasChimes/ChristmasChimes.mp3"
    },
    {
        "id": "597",
        "composer": "SCHUBERTFRANZ",
        "title": "Moments musicaux 1-6",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/SchubertMomentsMusicaux1-6",
        "mediaurl": "https://archive.org/download/SchubertMomentsMusicaux1-6/01_no.1InCMajor.mp3"
    },
    {
        "id": "2070",
        "composer": "SCHUBERTFRANZ",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Louise Homer",
        "pageurl": "https://archive.org/details/VrsAcoustics-88231-LouiseHomer",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88231-LouiseHomer/Homer_88231_64kb.mp3"
    },
    {
        "id": "8647",
        "composer": "STRAUSSRICHARD",
        "title": "J. Strauss, Jr.: One Lives But Once",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/J.StraussJr.OneLivesButOnce",
        "mediaurl": "https://archive.org/download/J.StraussJr.OneLivesButOnce/StraussOneLivesButOnce.mp3"
    },
    {
        "id": "404",
        "composer": "SCHUBERTFRANZ",
        "title": "Rosa Ponselle as Norma",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/RosaPonselleAsNorma",
        "mediaurl": "https://archive.org/download/RosaPonselleAsNorma/Bellini-norma-castaDiva.mp3"
    },
    {
        "id": "2137",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Feodor Chaliapin",
        "pageurl": "https://archive.org/details/VrsAcoustics-88645-FeodorChaliapin",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88645-FeodorChaliapin/Chaliapin_88645_64kb.mp3"
    },
    {
        "id": "1826",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Josef Hollman",
        "pageurl": "https://archive.org/details/VrsAcoustics-74044-JosefHollman",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74044-JosefHollman/Hollman_74044_64kb.mp3"
    },
    {
        "id": "1904",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Vladimir de Pachmann",
        "pageurl": "https://archive.org/details/VrsAcoustics-74285-VladimirDePachmann",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74285-VladimirDePachmann/DePachmann_74285_64kb.mp3"
    },
    {
        "id": "1824",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Marcel Journet",
        "pageurl": "https://archive.org/details/VrsAcoustics-74038-MarcelJournet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74038-MarcelJournet/Journet_74038_64kb.mp3"
    },
    {
        "id": "1942",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Flonzaley Quartet",
        "pageurl": "https://archive.org/details/VrsAcoustics-74578-FlonzaleyQuartet",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74578-FlonzaleyQuartet/FlonzaleyQuartet_74578_64kb.mp3"
    },
    {
        "id": "2048",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Ernestine Schumann-Heink",
        "pageurl": "https://archive.org/details/VrsAcoustics-88093-ErnestineSchumann-heink",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88093-ErnestineSchumann-heink/Schumann-Heink_88093.mp3"
    },
    {
        "id": "2006",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Pol Plancon",
        "pageurl": "https://archive.org/details/VrsAcoustics-85024-PolPlancon",
        "mediaurl": "https://archive.org/download/VrsAcoustics-85024-PolPlancon/Plancon_85024_64kb.mp3"
    },
    {
        "id": "1804",
        "composer": "SCHUMANNROBERT",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Vladimir de Pachmann",
        "pageurl": "https://archive.org/details/VrsAcoustics-6480a-VladimirDePachmann",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6480a-VladimirDePachmann/DePachmann_6480a_64kb.mp3"
    },
    {
        "id": "727",
        "composer": "SHOSTAKOVICHDMITRY",
        "title": "Symphony No. 6",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Shostakovich_symphony6",
        "mediaurl": "https://archive.org/download/Shostakovich_symphony6/Shostakovich6thStoky.mp3"
    },
    {
        "id": "1978",
        "composer": "SIBELIUSJEAN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-74698-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74698-PhiladelphiaSymphonyOrchestra/PhilSymph_74698_64kb.mp3"
    },
    {
        "id": "1386",
        "composer": "SIBELIUSJEAN",
        "title": "The Swan of Tuonela",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/TheSwanOfTuonela",
        "mediaurl": "https://archive.org/download/TheSwanOfTuonela/Sibelius_Ormandy_The_Swan_Of_Tuonela_64kb.mp3"
    },
    {
        "id": "1914",
        "composer": "SIBELIUSJEAN",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Maud Powell",
        "pageurl": "https://archive.org/details/VrsAcoustics-74408-MaudPowell",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74408-MaudPowell/Powell_74408_64kb.mp3"
    },
    {
        "id": "8874",
        "composer": "SIBELIUSJEAN",
        "title": "Lemminkainen's Journey",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Lemminkainens_Journey",
        "mediaurl": "https://archive.org/download/Lemminkainens_Journey/Lemminkainens_Journey_64kb.mp3"
    },
    {
        "id": "409",
        "composer": "STRAUSSRICHARD",
        "title": "Rosen aus dem Suden",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/RosenAusDemSuden",
        "mediaurl": "https://archive.org/download/RosenAusDemSuden/78rpmPublicDomain-JohannStraussSohn-RosenAusDemSdenteil1-BerlinerLehrer-gesangverein.mp3"
    },
    {
        "id": "1959",
        "composer": "STRAUSSRICHARD",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-74627-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74627-PhiladelphiaSymphonyOrchestra/PhilSymph_74627.mp3"
    },
    {
        "id": "2116",
        "composer": "STRAUSSRICHARD",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Frieda Hempel",
        "pageurl": "https://archive.org/details/VrsAcoustics-88540-FriedaHempel",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88540-FriedaHempel/Hempel_88540_64kb.mp3"
    },
    {
        "id": "1788",
        "composer": "STRAUSSRICHARD",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "New York Philharmonic Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-6427b-NewYorkPhilharmonicOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6427b-NewYorkPhilharmonicOrchestra/NYPhil_6427B_64kb.mp3"
    },
    {
        "id": "2028",
        "composer": "STRAUSSRICHARD",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Marcella Sembrich",
        "pageurl": "https://archive.org/details/VrsAcoustics-88019-MarcellaSembrich",
        "mediaurl": "https://archive.org/download/VrsAcoustics-88019-MarcellaSembrich/Sembrich_88019_64kb.mp3"
    },
    {
        "id": "1810",
        "composer": "STRAVINSKYIGOR",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-64926493-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-64926493-PhiladelphiaSymphonyOrchestra/PhilSymph_6492-93_64kb.mp3"
    },
    {
        "id": "1811",
        "composer": "STRAVINSKYIGOR",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-64926493-PhiladelphiaSymphonyOrchestra_240",
        "mediaurl": "https://archive.org/download/VrsAcoustics-64926493-PhiladelphiaSymphonyOrchestra_240/PhilSymph_6492-93_64kb.mp3"
    },
    {
        "id": "8790",
        "composer": "VERDIGIUSEPPE",
        "title": "La donna e mobile",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/La_donna_e_mobile",
        "mediaurl": "https://archive.org/download/La_donna_e_mobile/Caruso_La_donna_e_mobile_64kb.mp3"
    },
    {
        "id": "5977",
        "composer": "SULLIVANARTHUR",
        "title": "After dinner toast at Little Menlo",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0155-14",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0155-14/EDIS-SRP-0155-14.mp3"
    },
    {
        "id": "6823",
        "composer": "SULLIVANARTHUR",
        "title": "Gilbert & Sullivan: Trial by Jury",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/GilbertSullivanTrialByJury_696",
        "mediaurl": "https://archive.org/download/GilbertSullivanTrialByJury_696/GSTrialByJury.mp3"
    },
    {
        "id": "1260",
        "composer": "SULLIVANARTHUR",
        "title": "The Lost Chord 1912",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/The_Lost_Chord_1912",
        "mediaurl": "https://archive.org/download/The_Lost_Chord_1912/Caruso_The_Lost_Chord_1912_64kb.mp3"
    },
    {
        "id": "1259",
        "composer": "SULLIVANARTHUR",
        "title": "The Lost Chord",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/The_Lost_Chord",
        "mediaurl": "https://archive.org/download/The_Lost_Chord/Caruso_Lost_Chord_64kb.mp3"
    },
    {
        "id": "1021",
        "composer": "TCHAIKOVSKYPYOTRILY",
        "title": "Dance of the Flutes",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/TchaikovskyDanceOfTheFlutes",
        "mediaurl": "https://archive.org/download/TchaikovskyDanceOfTheFlutes/DanceOfTheFlutes.mp3"
    },
    {
        "id": "1787",
        "composer": "TCHAIKOVSKYPYOTRILY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "New York Philharmonic Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-6427a-NewYorkPhilharmonicOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6427a-NewYorkPhilharmonicOrchestra/NYPhil_6427A_64kb.mp3"
    },
    {
        "id": "4881",
        "composer": "TCHAIKOVSKYPYOTRILY",
        "title": "Pourquoi?",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoPourquoi",
        "mediaurl": "https://archive.org/download/CarusoPourquoi/Caruso_Pourquoi.mp3"
    },
    {
        "id": "1981",
        "composer": "TCHAIKOVSKYPYOTRILY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Philadelphia Symphony Orchestra",
        "pageurl": "https://archive.org/details/VrsAcoustics-74713-PhiladelphiaSymphonyOrchestra",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74713-PhiladelphiaSymphonyOrchestra/PhilSymph_74713_64kb.mp3"
    },
    {
        "id": "1817",
        "composer": "TCHAIKOVSKYPYOTRILY",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Feodor Chaliapin",
        "pageurl": "https://archive.org/details/VrsAcoustics-6532b-FeodorChaliapin",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6532b-FeodorChaliapin/Chaliapin_6532B_64kb.mp3"
    },
    {
        "id": "2742",
        "composer": "VERDIGIUSEPPE",
        "title": "Ah, La Paterna Mano",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Ah_La_Paterna_Mano",
        "mediaurl": "https://archive.org/download/Ah_La_Paterna_Mano/Ah_La_Paterna_Mano_64kb.mp3"
    },
    {
        "id": "8795",
        "composer": "VERDIGIUSEPPE",
        "title": "La Fatal Pietra",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/LaFatalPietra",
        "mediaurl": "https://archive.org/download/LaFatalPietra/La_fatal_pietra_64kb.mp3"
    },
    {
        "id": "9243",
        "composer": "VERDIGIUSEPPE",
        "title": "Mai Reggendo All'Aspro",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Mai_Reggendo_AllAspro",
        "mediaurl": "https://archive.org/download/Mai_Reggendo_AllAspro/Caruso_Mai_reggendo_Allaspro_assalto_64kb.mp3"
    },
    {
        "id": "4870",
        "composer": "VERDIGIUSEPPE",
        "title": "Gia i sacerdoti adunansi",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoGiaISacerdotiAdunansi",
        "mediaurl": "https://archive.org/download/CarusoGiaISacerdotiAdunansi/Caruso_Gia_I_Sacerdoti_Adunansi_64kb.mp3"
    },
    {
        "id": "4908",
        "composer": "VERDIGIUSEPPE",
        "title": "Celeste Aida 1908",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/CelesteAida1908",
        "mediaurl": "https://archive.org/download/CelesteAida1908/Celeste_Aida_1908_64kb.mp3"
    },
    {
        "id": "1962",
        "composer": "VERDIGIUSEPPE",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Alfred Cortot",
        "pageurl": "https://archive.org/details/VrsAcoustics-74636-AlfredCortot",
        "mediaurl": "https://archive.org/download/VrsAcoustics-74636-AlfredCortot/Cortot_74636_64kb.mp3"
    },
    {
        "id": "9832",
        "composer": "VERDIGIUSEPPE",
        "title": "Niun Mi Tema (Morte D'Othello)",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/niunmitema1903",
        "mediaurl": "https://archive.org/download/niunmitema1903/niunmitema1903.mp3"
    },
    {
        "id": "6473",
        "composer": "VERDIGIUSEPPE",
        "title": "Forza del Destino",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ForzaDelDestino",
        "mediaurl": "https://archive.org/download/ForzaDelDestino/Forza_del_Destino_64kb.mp3"
    },
    {
        "id": "4866",
        "composer": "VERDIGIUSEPPE",
        "title": "Ai Nostri monti",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Caruso",
        "pageurl": "https://archive.org/details/CarusoAiNostriMonti",
        "mediaurl": "https://archive.org/download/CarusoAiNostriMonti/Caruso_Ai_nostri_monti_64kb.mp3"
    },
    {
        "id": "10058",
        "composer": "VERDIGIUSEPPE",
        "title": "O terra addio",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/O_terra_addio",
        "mediaurl": "https://archive.org/download/O_terra_addio/O_terra_addio_64kb.mp3"
    },
    {
        "id": "11199",
        "composer": "VERDIGIUSEPPE",
        "title": "Ah! fors' e lui - La traviata",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-WXT-02",
        "mediaurl": "https://archive.org/download/EDIS-WXT-02/EDIS-WXT-02.mp3"
    },
    {
        "id": "9783",
        "composer": "VERDIGIUSEPPE",
        "title": "Nell'ore Arcane Della Sua Lussuria",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Nellore_Arcane_Della_Sua_Lussuria",
        "mediaurl": "https://archive.org/download/Nellore_Arcane_Della_Sua_Lussuria/Caruso_Nellore_arcane_della_sua_luss_64kb.mp3"
    },
    {
        "id": "2746",
        "composer": "VERDIGIUSEPPE",
        "title": "Ah, si ben mio",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/AhSiBenMio",
        "mediaurl": "https://archive.org/download/AhSiBenMio/Ah_si_ben_mio.mp3"
    },
    {
        "id": "257",
        "composer": "VERDIGIUSEPPE",
        "title": "",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "Jose Mardones",
        "pageurl": "https://archive.org/details/VrsAcoustics-6420a-JoseMardones",
        "mediaurl": "https://archive.org/download/VrsAcoustics-6420a-JoseMardones/Mardones_6420A_64kb.mp3"
    },
    {
        "id": "1777",
        "composer": "VIVALDIANTONIO",
        "title": "Concerto in D Major",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Vivaldi-bachConcertoInDMajor",
        "mediaurl": "https://archive.org/download/Vivaldi-bachConcertoInDMajor/1.Allegro.mp3"
    },
    {
        "id": "6032",
        "composer": "WAGNERRICHARD",
        "title": "Ride of the Valkyries",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0197-06",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0197-06/EDIS-SRP-0197-06.mp3"
    },
    {
        "id": "6005",
        "composer": "WAGNERRICHARD",
        "title": "Hochstes vertrauen - Lohengrin",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0194-07",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0194-07/EDIS-SRP-0194-07.mp3"
    },
    {
        "id": "6006",
        "composer": "WAGNERRICHARD",
        "title": "O, tannenbaum",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/EDIS-SRP-0194-08",
        "mediaurl": "https://archive.org/download/EDIS-SRP-0194-08/EDIS-SRP-0194-08.mp3"
    },
    {
        "id": "10324",
        "composer": "PROKOFIEVSERGEI",
        "title": "Peter and the Wolf",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/PeterAndTheWolf_753",
        "mediaurl": "https://archive.org/download/PeterAndTheWolf_753/PeterAndTheWolf_01.mp3"
    },
    {
        "id": "9845",
        "composer": "CHOPINFRYDERYK",
        "title": "Nocturne in E-Flat",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/NocturneInE-flat",
        "mediaurl": "https://archive.org/download/NocturneInE-flat/NocturneInE-flat_64kb.mp3"
    },
    {
        "id": "3605",
        "composer": "SULLIVANARTHUR",
        "title": "Arthur Sullivan",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/ArthurSullivan",
        "mediaurl": "https://archive.org/download/ArthurSullivan/13-PersonalRecordToMr.Edison1888_64kb.mp3"
    },
    {
        "id": "7946",
        "composer": "VERDIGIUSEPPE",
        "title": "Ingemisco",
        "year": "",
	"genre": "classical",
        "form": "30",
        "performer": "",
        "pageurl": "https://archive.org/details/Ingemisco",
        "mediaurl": "https://archive.org/download/Ingemisco/Ingemisco_64kb.mp3"
    }
]}
